### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#317]
*NOTE! Prior to doing a code review, copy this checklist to a GitHub issue for the repository being reviewed.*
*Please mark failed items with ❌*

PhET code-review checklist
=============

#### **Build and Run Checks**

- [x] Does the sim build without warnings or errors?
- [x] Does the html file size seem reasonable, compared to other similar sims?
- [x] Does the sim start up? (requirejs and built versions)
- [x] Does the sim experience any assertion failures? (run with query parameter `ea`)
- [x] Does the sim pass a scenery fuzz test? (run with query parameters `fuzzMouse&ea`)

#### **Memory Leaks**

- [x] Does a heap comparison using Chrome Developer Tools indicate a memory leak? (Describing this process is beyond the scope of this document.) There should be a GitHub issue showing the results of testing done by the primary developer.
- [x] For each common-code component (sun, scenery-phet, vegas, …) that opaquely registers observers or listeners, is there a call to that component’s `dispose` function, or documentation about why `dispose` is unnecessary?
- [x] Are there leaks due to registering observers or listeners? These guidelines should be followed, or documentation added about why following them is not necessary:
	- [x] AXON: `Property.link` is accompanied by `Property.unlink`.
	- [x] AXON: `PropertySet.link` is accompanied by `PropertySet.unlink`.
	- [x] AXON: Creation of `DerivedProperty` is accompanied by `dispose`.
	- [x] AXON: Creation of `Multilink` is accompanied by `dispose`.
	- [x] AXON: `Events.on` is accompanied by `Events.off`.
	- [x] AXON: `Emitter.addListener` is accompanied by `Emitter.removeListener`.
	- [x] SCENERY: `Node.on` is accompanied by `Node.off`
	- [x] TANDEM: `tandem.addInstance` is accompanied by `tandem.removeInstance`.
- [x] Do all types that require a `dispose` function have one? This should expose a public `dispose` function that calls `this.disposeMyType()`, where `disposeMyType` is a private function declared in the constructor.  `MyType` should exactly match the filename.
- [x] PhET-iO instantiates different objects and wires up listeners that are not present in the PhET-branded simulation.  It needs
      to be tested separately for memory leaks.  To help isolate the nature of the memory leak, this test should be run separately
      from the PhET brand memory leak test.  Test with the "console" and "instance proxies" wrappers (easily accessed from phetmarks)

#### **Performance, Usability**

- [x] Does the sim perform as desired across the range of supported platforms? (eg, not too slow on slow platforms, not too fast on fast platforms)
- [x] If the sim uses WebGL, does it have a fallback? Does the fallback perform reasonably well? (run with query parameter `webgl=false`)
- [x] Are UI components sufficiently responsive? (especially continuous UI components, such as sliders)
- [x] Are pointer areas optimized, especially for touch? (run with query parameter `showPointerAreas`)
- [x] Do pointer areas overlap? (run with query parameter `showPointerAreas`)

#### **Internationalization**
- [x] Are there any strings that are not being internationalized? (run with query parameter `stringTest=x`, you should see nothing but 'x' strings)
- [x] Does the sim layout gracefully handle internationalized strings that are twice as long as the English strings? (run with query parameter `stringTest=double`)
- [x] Does the sim layout gracefully handle internationalized strings that are exceptionally long? (run with query parameter `stringTest=long`)
- [x] Does the sim layout gracefully handle internationalized strings that are shorter than the English strings? (run with query parameter `stringTest=X`)
- [x] Does the sim stay on the sim page (doesn't redirect to an external page) when running with the query parameter `stringTest=xss`? This test passes if sim does not redirect, OK if sim crashes or fails to fully start. Only test on one desktop platform.
- [x] Use named placeholders (e.g. `"{{value}} {{units}}"`) instead of numbered placeholders (e.g. `"{0} {1}"`).
- [x] Make sure the string keys are all perfect - they are difficult to change after 1.0.0 is published.  Strings keys should generally match their values, such as `"binaryProbability": { "value": "Binary Probability" }`. 
- [x] String keys for screen names should have the general form `"screen.{{screenName}}"`, e.g. `"screen.lab"`. 
- [x] String patterns that contain placeholders (e.g. `"My name is {{first}} {{last}}"`) should use keys that are unlikely to conflict with strings that might be needed in the future.  For example, for `"{{price}}"` consider using key `"pricePattern"` instead of `"price"`, if you think there might be a future need for a `"price"` string.

#### **Repository structure**

- [x] Are all required files and directories present?
For a sim repository named “my-repo”, the general structure should look like this (where assets/, audio/ or images/ may be omitted if the sim doesn’t have those types of assets).

```js
   my-repo/
      assets/
      audio/
         license.json
      doc/
         model.md
         implementation-notes.md
      images/
         license.json
      js/
         (see section below)
      dependencies.json
      .gitignore
      my-repo_en.html
      my-repo-strings_en.json
      Gruntfile.js
      LICENSE
      package.json
      README.md
```

   For a common-code repository, the structure is similar, but some of the files and directories may not be present if the repo doesn’t have audio, images, strings, or a demo application.

- [x] Is the js/ directory properly structured?
All JavaScript source should be in the js/ directory. There should be a subdirectory for each screen (this also applies for single-screen sims, where the subdirectory matches the repo name).  For a multi-screen sim, code shared by 2 or more screens should be in a js/common/ subdirectory. Model and view code should be in model/ and view/ subdirectories for each screen and common/.  For example, for a sim with screens “Introduction” and “Lab”, the general directory structure should look like this:

```js
   my-repo/
      js/
         common/
            model/
            view/
         introduction/
            model/
            view/
         lab/
            model/
            view/
         my-repo-config.js
         my-repo-main.js
         myRepo.js
 ```

- [x] Is there a file in assets/ for every resource file in audio/ and images/? Note that there is *not necessarily* a 1:1 correspondence between asset and resource files; for example, several related images may be in the same .ai file. Check license.json for possible documentation of why some reesources might not have a corresponding asset file.
- [x] Was the README.md generated by `grunt published-README` or `grunt unpublished-README`?
- [x] Does package.json refer to any dependencies that are not used by the sim?
- [x] Does sim-config.js refer to any dependencies that are not used by the sim? Note: `ifphetio` plugin and `PHET_IO` dependencies should be included in all config files.
- [x] Does package.json contain phetLibs for all non-default entries in sim-config.json? 
- [x] Is the LICENSE file correct? (GPL v3 for sims, MIT for common code)
- [x] Does .gitignore match the one in simula-rasa?
- [x] Does a GitHub issue exist for tracking credits, to ensure that they are correct before publication?
- [x] In GitHub, verify that all non-release branches have an associated issue that describes their purpose.
- [x] Are there any GitHub branches that are no longer needed and should be deleted?
- [x] Does `model.md` adequately describe the model, in terms appropriate for teachers?
- [x] Does `implementation-notes.md` adequately describe the implementation, with an overview that will be useful to future maintainers?
- [x] Are sim-specific query parameters (if any) identified and documented in one .js file in js/common/ or js/ (if there is no common/)? The .js file should be named `{{REPO}}QueryParameters.js`, for example ArithmeticQueryParameters.js for the aritmetic repository.

#### **Coding Conventions**

- [x] Is the code formatted according to PhET conventions? See [phet-idea-code-style.xml](https://github.com/phetsims/joist/blob/master/util/phet-idea-codestyle.xml) for IntelliJ IDEA code style.
- [x] Are copyright headers present and up to date? Run `grunt update-copyright-dates`.
- [x] Names (types, variables, properties, functions,...) should be sufficiently descriptive and specific, and should avoid non-standard abbreviations. For example:

```js
var numPart;            // incorrect
var numberOfParticles;  // correct

var width;              // incorrect
var beakerWidth;        // correct
```

- [x] Require statements should be organized into blocks, with the code modules first, followed by strings, images and audio (any order ok for strings/images/audio).  For modules, the var name should match the file name. Example below.

```js
// modules
var inherit = require( 'PHET_CORE/inherit' );
var Line = require( 'SCENERY/nodes/Line' );
var Rectangle = require( 'SCENERY/nodes/Rectangle' );

// strings
var kineticString = require( 'string!ENERGY/energy.kinetic' );
var potentialString = require( 'string!ENERGY/energy.potential' );
var thermalString = require( 'string!ENERGY/energy.thermal' );

// images
var energyImage = require( 'image!ENERGY/energy.png' );

// audio
var kineticAudio = require( 'audio!ENERGY/energy' );
```

- [x] Do the `@author` annotations seem correct? 

- [x] For constructors, use parameters for things that don’t have a default. Use options for things that have a default value.  This improves readability at the call site, especially when the number of parameters is large.  It also eliminates order dependency that is required by using parameters.

For example, this constructor uses parameters for everything. At the call site, the semantics of the arguments are difficult to determine without consulting the constructor.

```js
/**
 * @param {Ball} ball - model element
 * @param {Property.<boolean>} visibleProperty - is the ball visible?
 * @param {Color|string} fill - fill color
 * @param {Color|string} stroke - stroke color
 * @param {number} lineWidth - width of the stroke
 * @constructor
 */
function BallNode( ball, visibleProperty, fill, stroke, lineWidth ){
   // ...
}

// Call site
var ballNode = new BallNode( ball, visibleProperty, 'blue', 'black', 2 );
```
Here’s the same constructor with an appropriate use of options. The call site is easier  to read, and the order of options is flexible.

```js
/**
 * @param {Ball} ball - model element
 * @param {Property.<boolean>} visibleProperty - is the ball visible?
 * @param {Object} [options]
 * @constructor
 */
function BallNode( ball, visibleProperty, options ) {

  options = _.extend( {
    fill: 'white',  // {Color|string} fill color
    stroke: 'black', // {Color|string} stroke color
    lineWidth: 1 // {number} width of the stroke
  }, options ); 

  // ...
}

// Call site
var ballNode = new BallNode( ball, visibleProperty, {
  fill: 'blue', 
  stroke: 'black', 
  lineWidth: 2 
} );
```

- [x] Constructor and function documentation.  Parameter types and names should be clearly specified for each function and constructor (if there are any parameters) using `@param` annotations.  The description for each parameter should follow a hyphen.  Primitive types should use lower case.  Constructors should additionally include the `@constructor` annotation. For example:

```js
/** 
 * The PhetDeveloper is responsible for creating code for simulations
 * and documenting their code thoroughly.
 * 
 * @param {string} name - full name
 * @param {number} age - age, in years
 * @param {boolean} isEmployee - whether this developer is an employee of CU
 * @param {function} callback - called immediate after coffee is consumed
 * @param {Property.<number>} hoursProperty - cumulative hours worked
 * @param {string[]} friendNames - names of friends
 * @param {Object} [options] - optional configuration, see constructor
 * @constructor
 */
function PhetDeveloper( name, age, isEmployee, callback, hoursProperty, friendNames, options ) {}
```

- [x] For most functions, the same form as above should be used, with a `@returns` annotation which identifies the return type and the meaning of the returned value.  Functions should also document any side effects.  For extremely simple functions that are just a few lines of simple code, an abbreviated line-comment can be used, for example: `// Computes {Number} distance based on {Foo} foo.`

- [x] If references are needed to the enclosing object, such as for a closure, `self` should be defined, but it should only be used in closures.  The `self` variable should not be defined unless it is needed in a closure.  Example:

```js
var self = this;
someProperty.link( function(){
  self.doSomething();
} );
this.doSomethingElse();
```

- [x] Generally, lines should not exceed 120 columns. Break up long statements, expressions, or comments into multiple
lines to optimize readability.  It is OK for require statements or other structured patterns to exceed 120 columns.  
Use your judgment!   

- [x] Where inheritance is needed, use `PHET_CORE/inherit`. Add prototype and static functions via the appropriate arguments to `inherit`. Spaces should exist between the function names unless the functions are all short and closely related.  Example:

```js
  return inherit( Object, Line, {

   /**
    * Gets the slope of the line
    * @returns {number}
    */
    getSlope: function() {
      if ( this.undefinedSlope() ) {
        return Number.NaN;
      }
      else {
        return this.rise / this.run;
      }
    },

    /**
     * Given x, solve y = m(x - x1) + y1.  Returns NaN if the solution is not unique, or there is no solution (x can't 
     * possibly be on the line.)  This occurs when we have a vertical line, with no run.
     * @param {number} x - the x coordinate
     * @returns {number} the solution
     */
    solveY: function( x ) {
      if ( this.undefinedSlope() ) {
        return Number.NaN;
      }
      else {
        return ( this.getSlope() * ( x - this.x1 ) ) + this.y1;
      }
    }
  } );
```

- [x] Functions should be invoked using the dot operator rather than the bracket operator.  For more details, please see https://github.com/phetsims/gravity-and-orbits/issues/9. For example:
```js
// avoid
self[ isFaceSmile ? 'smile' : 'frown' ]();

// OK
isFaceSmile ? self.smile() : self.frown();

// OK
if ( isFaceSmile ) {
  self.smile();
}
else {
  self.frown();
}
```

- [x] It is not uncommon to use conditional shorthand and short circuiting for invocation. 

```js
( expression ) && statement;
( expression ) ? statement1 : statement2;
( foo && bar ) ? fooBar() : fooCat();
( foo && bar ) && fooBar();
( foo && !(bar && fooBar)) && nowIAmConfused();
this.fill = ( foo && bar ) ? 'red' : 'blue'; 
```

If the expression is only one item, the parentheses can be omitted. This is the most common use case.

```js
assert && assert( happy, ‘Why aren\’t you happy?’ );
happy && smile();
var thoughts = happy ? ‘I am happy’ : ‘I am not happy :(’;
```

- [x] Naming for Property values:  All `AXON/Property` instances should be declared with the suffix `Property`.  For example, if a visible property is added, it should have the name `visibleProperty` instead of simply `visible`.  This will help to avoid confusion with non-Property definitions.

- [x] Line comments should be preceded by a blank line.  For example:

```js
// Randomly choose an existing crystal to possibly bond to
var crystal = this.crystals.get( _.random( this.crystals.length - 1 ) );

// Find a good configuration to have the particles move toward
var targetConfiguration = this.getTargetConfiguration( crystal );
```

- [x] Line comments should have whitespace between the `//` and the first letter of the line comment.  See the preceding example.

- [x] Differentiate between `Property` and "property" in comments. They are different things. `Property` is a type in AXON; property is any value associated with a JavaScript object.

- [x] Files should be named like CapitalizedCamelCasing.js when returning a constructor, or lower-case-style.js when returning a non-constructor function.  When returning a constructor, the constructor name should match the filename.

- [x] Every type, method and property should be documented.

- [x] The HTML5/CSS3/JavaScript source code must be reasonably well documented.  This is difficult to specify precisely, but the idea is that someone who is moderately experienced with HTML5/CSS5/JavaScript can quickly understand the general function of the source code as well as the overall flow of the code by reading through the comments.  For an example of the type of documentation that is required, please see the example-sim repository.

##### Visibility Annotations
Because JavaScript lacks visibility modifiers (public, protected, private), PhET uses JSdoc visibility annotations to document the intent of the programmer, and define the public API. Visibility annotations are required for anything that JavaScript makes public. Information about these annotations can be found here. (Note that other documentation systems like the Google Closure Compiler use slightly different syntax in some cases. Where there are differences, JSDoc is authoritative. For example, use `Array.<Object>` or `Object[]` instead of `Array<Object>`). PhET guidelines for visibility annotations are as follows:

- [x] Use `@public` for anything that is intended to be part of the public API.
- [x] Use `@protected` for anything that is intended for use by subtypes.
- [x] Use `@private` for anything that is NOT intended to be part of the public or protected API.
- [x] Put qualifiers in parenthesis after the annotation, for example:
- [x] To qualify that something is read-only, use `@public (read-only)`. This indicates that the given property (AND its value) should not be changed by outside code (e.g. a Property should not have its value changed)
- [x] To qualify that something is public to a specific repository, use (for example) `@public (scenery-internal)`
- [x] Separate multiple qualifiers with commas. For example: `@public (scenery-internal, read-only)`

- [x] For JSDoc-style comments, the annotation should appear in context like this:

```js
/**
 * Creates the icon for the "Energy" screen, a cartoonish bar graph.
 * @returns {Node}
 * @public
 */
```

- [x] For Line comments, the annotation can appear like this:

```js
// @public Adds a {function} listener
addListener: function( listener ) { /*...*/ }
```

- [x] Verify that every JavaScript property and function has a visibility annotation. Here are some helpful regular expressions to search for these declarations as PhET uses them.
* Regex for property assignment like `x.y = something`: `[\w]+\.[\w]+\s=`
* Regex for function declarations: `[\w]+: function\(`

#### **Math Libraries**

- [x] Check that `dot.Util.roundSymmetric` is used instead of `Math.round`. `Math.round` does not treat positive and negative numbers symmetrically, see https://github.com/phetsims/dot/issues/35#issuecomment-113587879.
- [x] `DOT/Util.toFixed` or `DOT/Util.toFixedNumber` should be used instead of `toFixed`. JavaScript's `toFixed` is notoriously buggy. Behavior differs depending on browser, because the spec doesn't specify whether to round or floor.
- [x] Check that random numbers are generated using `phet.joist.random`, and are doing so after modules are declared (non-statically).  For example, the following methods (and perhaps others) should not be used:
* `Math.random`
* `_.shuffle`
* `_.sample`
* `_.random`
* `new Random()`

#### **Organization, Readability, Maintainability**

- [x] Does the organization and structure of the code make sense? Do the model and view contain types that you would expect (or guess!) by looking at the sim? Do the names of things correspond to the names that you see in the user interface?
- [x] Are appropriate design patterns used?
- [x] Is inheritance used where appropriate? Does the type hierarchy make sense?
- [x] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)
- [x] Is there too much unnecessary decoupling? (e.g. by passing all of the properties of an object independently instead of passing the object itself)?
- [x] Are the source files reasonable in size? Scrutinize large files with too many responsibilities - can responsibilities be broken into smaller delegates?
- [x] Are any significant chunks of code duplicated? This will be checked manually as well as with https://github.com/danielstjules/jsinspect or `grunt find-duplicates`
- [x] Is there anything that should be generalized and migrated to common code?
- [x] Are there any `TODO` or `FIXME` comments in the code?  They should be addressed or promoted to GitHub issues.
- [x] Does the implementation rely on any specific constant values that are likely to change in the future? Identify constants that might be changed in the future. (Use your judgement about which constants are likely candidates.) Does changing the values of these constants break the sim? For example, see https://github.com/phetsims/plinko-probability/issues/84.
- [x] The simulation should use `Property` instead of `PropertySet`.
- [x] Are all dependent properties modeled as `DerivedProperty` instead of `Property`?

#### **PhET-iO**

- [x] If the simulation is supposed to be instrumented for PhET-iO, please see [How to Instrument a PhET Simulation for PhET-iO](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md)
for the PhET-iO development process.

**Comment by samreid** [comment]
@ariel-phet requested @jonathanolson to code review this when the time is right.

**Comment by samreid** [comment]
@ariel-phet mentioned that it is sometimes good to have at least dev testing complete before code review.

**Comment by ariel-phet** [comment]
Clearing assignees until sim is ready for review

**Comment by samreid** [comment]
Notes for the review:
1. There are TODO (phet-io) or TODO (black-box-study) marked in the source code.  In my opinion, these do not need to be resolved prior to publication of 1.0.
2. both the circuit-construction-kit-common and circuit-construction-kit-dc repos need to be reviewed.

**Comment by samreid** [comment]
Questions for the reviewer:

1. Why do the pointer areas for the schematic elements have to be translated?  See https://github.com/phetsims/circuit-construction-kit-dc/issues/93

**Comment by jonathanolson** [comment]
Reminder to add the checklist to the top comment.

**Comment by samreid** [comment]
Copied top comment so the top comment can become the checklist:

We are hoping to publish this simulation by the end of July, so we should get ready to schedule the code review.  Choosing a code reviewer now could also help me when I run into technical issues if I need to consult with someone (even if that is before the code review).  Here's my estimate at a timeline as it pertains to the code review:

June 26 code review begins
June 30 code review ends

I'd love to start the code review a week earlier (to give more time to address issues and go through QA) but I doubt the sim will be feature complete by then.

Assigned to @ariel-phet so he is aware of the potential timeline and can start scheduling a reviewer.

**Comment by samreid** [comment]
I moved the checklist to the top comment so its summary will show in the issue overview.

@jonathanolson this sim is ready for review.

**Comment by samreid** [comment]
> //REVIEW: Don't see any read/link to this, maybe there is something I'm missing?

At one point we were thinking of highlighting the toolbox when something can be dropped into it, but it was odd that the toolbox highlighted right when a circuit element was dropped out, so we abandoned that idea.  I'll remove it.

**Comment by samreid** [comment]
The preceding commit would be a good one for @jonathanolson to look at more closely.

**Comment by samreid** [comment]
The preceding commit wasn't addressed in exactly the prescribed way, would be good for you to check it @jonathanolson.

**Comment by samreid** [comment]
The preceding commit moved review comments to PhET-iO TODOs, is that OK?

**Comment by samreid** [comment]
The preceding commit would also be good to review, since I use a `get` method instead of `getStartPositionProperty()` method.

**Comment by samreid** [comment]
I'm hoping that @jonathanolson can review pretty much all of my commits that attempt to address review comments.

**Comment by samreid** [comment]
@jonathanolson I'm using `REVIEW*` to indicate the ball is in my court for a thread and `REVIEW^` for threads that are ready for you.

**Comment by samreid** [comment]
In the preceding commit, I switched Vertex constructor to take Vector2, but after seeing the many call sites, I was no longer convinced that was best.  @jonathanolson can you please review the preceding commit and make a recommendation?

**Comment by samreid** [comment]
The REVIEW comment addressed in the preceding commit said `For memory/performance purposes, it looks like this should be a method instead of creating a function` but the proposed solution still creates a function using `bind`, is that what was intended?

**Comment by jonathanolson** [comment]
> In the preceding commit, I switched Vertex constructor to take Vector2, but after seeing the many call sites, I was no longer convinced that was best. @jonathanolson can you please review the preceding commit and make a recommendation?

New code:
```js
var vertex = new Vertex( new Vector2( circuitState.vertices[ i ].x, circuitState.vertices[ i ].y ), options );
```

Presumably there's a good phetio-way of deserializing Vector2s so we don't have to do this ourself?

```js
        startVertex: createVertex( new Vector2( position.x - length / 2, position.y ) ),
        endVertex: createVertex( new Vector2( position.x + length / 2, position.y ) )
```
could become:
```js
        startVertex: createVertex( position.minusXY( length / 2, 0 ) ),
        endVertex: createVertex( position.plusXY( length / 2, 0 ) )
```

If the objection is that lots of manual x-y pairs are included, either:

1. Have a factory method `Vertex.createXY( x, y )`
2. Allow a constructor `new Vertex( x, y )` if x is a number (polymorphic directly)
3. Revert, but internally in Vertex create ONLY one Vector2 (and live with the extra Vector2 allocations made that need to be converted to x,y).

**Comment by jonathanolson** [comment]
> The REVIEW comment addressed in the preceding commit said For memory/performance purposes, it looks like this should be a method instead of creating a function but the proposed solution still creates a function using bind, is that what was intended?

Yes, bind looks better for memory (see https://github.com/phetsims/scenery/issues/664), and it should just create a reference to a function (cheaper than a function object presumably).

**Comment by jonathanolson** [comment]
@samreid I've reviewed all of your commits above that you explicitly commented that I should review. Let me know if I should review all of the others. (I'd prefer to trust your judgment and not review).

**Comment by samreid** [comment]
Sounds good, I tried to call out the iffy ones.

**Comment by samreid** [comment]
I simplified 2 Vertex Vector call sites above.  Regarding:

> Presumably there's a good phetio-way of deserializing Vector2s so we don't have to do this ourself?

I'll leave this line as-is for now, since we may need a non-phet-io way to serialize for the CCK PhET app.

**Comment by samreid** [comment]
@jonathanolson can you please review the preceding commit?

**Comment by samreid** [comment]
@jonathanolson can you please review the preceding commit?

**Comment by samreid** [comment]
@jonathanolson can you please review the preceding commit?

**Comment by samreid** [comment]
@jonathanolson can you please review the preceding commit?

**Comment by samreid** [comment]
It took a number of commits to get there, but I converted from the many filters to one filter (with a supplemental filter for black box study).  @jonathanolson can you please review Circuit.getDropTarget and let me know what you recommend?

**Comment by samreid** [comment]
Likewise, I switched to an array-based reference ID (no longer sorted), @jonathanolson can you check it out?

**Comment by samreid** [comment]
In the preceding commit, I changed CircuitElementToolbox so that clients specify the carousel items, it would be good for @jonathanolson to take a look and make further recommendations.

**Comment by samreid** [comment]
@jonathanolson I finished all of the `REVIEW*` items, so the ball is back in your court.

**Comment by samreid** [comment]
@jonathanolson I finished all of the `REVIEW*` items, so the ball is back in your court.

**Comment by jonathanolson** [comment]
> String keys for screen names should have the general form "screen.{{screenName}}", e.g. "screen.lab".

Keys are 'intro' and 'lab' right now, will need prefixes.

**Comment by jonathanolson** [comment]
Code review (pending any existing REVIEW notes and issues) is complete.

Looks great!

**Comment by samreid** [comment]
REVIEW comments and issue comments have been addressed, and remaining work is identified in open issues, closing.
