### ISSUE TITLE
Publish CCK AC 1.0 by January 31, 2020

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-common#449]
Today I asked if there was a deadline for publication of CCK AC 1.0, and the answer was Jan 2020.  It was noted that publishing by summer would be much better, but it was also requested to finish the Diffraction screen by the end of summer and I can't say it's feasible to do both by then.

UPDATE: Last week we clarified this sim needs to be published by the end of January 2020, and I sent @kathy-phet a time estimate.

- [x] AC Voltage source
- [x] Port the AC model, see https://github.com/phetsims/circuit-construction-kit-common/issues/439
- [ ] Voltage and current charts, see other issues
- [ ] AC source should have settable internal resistance on lab screen and phase control
- [x] Add capacitor model
- [x] Add capacitor view, see https://github.com/phetsims/circuit-construction-kit-common/issues/452
- [ ] capacitor edit controls should have a way to clear
- [ ] Add inductors, model + view, see #537 #503 
- [ ] inductor edit controls should have a way to clear
- [x] Triage all open issues
- [x] Review the design doc to see what else remains to be done
- [ ] Stopwatch, see https://github.com/phetsims/scenery-phet/issues/530 and https://github.com/phetsims/gas-properties/issues/170
- [x] 6 carousel slots
- [ ] Change the order of carousel items
- [x] Add a 2nd screen
- [x] Scene selection buttons different location than in DC: UPDATE: Decided against in https://github.com/phetsims/circuit-construction-kit-common/issues/505
- [ ] Address as many non-deferred issues as possible

**Comment by samreid** [comment]
@kathy-phet additionally asked for an estimate of developer hours for this.

**Comment by arouinfar** [comment]
@samreid I reviewed the design doc, and it's up to date. I also can't think of anything that needs to be added to the checklist in https://github.com/phetsims/circuit-construction-kit-common/issues/449#issue-410590256

**Comment by samreid** [comment]
All problems noted here are listed in other issues, closing.
