### ISSUE TITLE
Circuit Construction Kit Basics master checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-common#8]
## Design
- [x] **Design doc created** (Date: 01/03/2014) 
  - [x] Make phethelp@gmail.com owner, share with phet-team
  - [ ] Add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [x] **Learning goals and standards identified** (Date: 10/14/2015)
- [x] **Design concept complete**  (Date: 01/07/2016)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide
  - [ ] Add an activity
  - [ ] Update [Gooru spreadsheet](https://docs.google.com/spreadsheets/d/13qvc7e71zTTjaJ2VcYhhU0rNxvH4kYFnoScVCOvvf7U/edit#gid=1717560774)
  - [ ] Sim primer
  - [ ] Verify credits
- [ ] **Add to Edmodo**
- [ ] **Hold postmortem if applicable** (Date: //) 
## Implementation
- [x] **Sim repo created** (Date: 05/14/2014) 
  - [x] Collaborators added (such as QA team, designers, etc) 
  - [ ] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [ ] Port existing strings (IF ANY) and commit to the GitHub repo
- [x] **Initial development started** (Date: 10/15/2015)
- [ ] **Sim feature complete** (Date: //) 
- [ ] **Code review complete** (Date: //) 
  - [ ] Code review checklist
  - [ ] Model description 
- [ ] **Published** (Date: //) 
  - [ ] Update repo README to published template
## QA
- [ ] **Dev testing complete** (Date: //) 
- [ ] **First release candidate** (Date: //)
  - [ ] phethelp@gmail.com owner of test matrix, share with phet-team, add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
  - [ ] Test matrix deemed complete

**Comment by ariel-phet** [comment]
Note -- using the "new sim" checklist even though this has some aspects of a port.

**Comment by samreid** [comment]
Moved to https://github.com/phetsims/circuit-construction-kit-basics/issues/1, closing.
