### ISSUE TITLE
Update Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-common#886]
The Teacher Tips should be updated with the next release.

- [x] Remove `moreWires` from query parameter table, #884 
- [x] Add `ammeterReadout` to query parameter table
- [x] Remove info related to hand & dog, #882 #907 
- [x] Update references to precision, see #963 
- [x] Update screenshots

**Comment by arouinfar** [comment]
This issue should wait until we are in RC testing. It does not block publication in any way.

**Comment by arouinfar** [comment]
The Teacher Tips have been updated and are ready to upload once the sim is redeployed.

**Comment by arouinfar** [comment]
Teacher Tips for CCK:DC - Virtual Lab have been uploaded to the site, closing.
